version: '3'

services:
    ideaspacevr:
        container_name: ideaspacevr
        image: knospi/ideaspacevr
        build:
            context: "./"
            dockerfile: Dockerfile
            args:
                ideaspacevr_version: "1.2.2"
                PROXY_ROOT_URL: ""
        ports:
         - 4832:80
        volumes:
#          - "./database.php:/var/www/html/config/database.php"
          - "./assets/user/:/var/www/html/public/assets/user/"
        environment:
          - PROXY_SCHEMA=http
        networks:
          - database_network


networks:
  database_network:
    external:
      name: mysql_default
